image: python:3.7
before_script:
  - apk add --no-cache --update python3-dev gcc build-base
  - python --version
  - python setup.py develop

stages:
  - analysis:flake8
  - analysis:pylint

.defflake8: &defflake8
  script:
    - pip install flake8
    - flake8
  stage: analysis:flake8

flake8:python3.5:
  <<: *defflake8
  image: python:3.5-alpine

flake8:python3.6:
  <<: *defflake8
  image: python:3.6-alpine

flake8:python3.7:
  <<: *defflake8
  image: python:3.7-alpine