image: python:3.7
before_script:
  - python --version
  - python setup.py develop
  - pip install pylint flake8

stages:
  - analysis:flake8
  - analysis:pylint

.defflake8: &defflake8
  script:
    - flake8
  stage: analysis:flake8

flake8:python3.5:
  <<: *defflake8
  image: python:3.5-alpine

flake8:python3.6:
  <<: *defflake8
  image: python:3.6-alpine

flake8:python3.7:
  <<: *defflake8
  image: python:3.7-alpine